### ISSUE TITLE
Getting Error Testing Locally

### ISSUE THREAD

**Issue by frogydiak** [adaptcms/AdaptCMS#60]
Hi There!

This is a nice project you're working on. I got curious and tried it but I got an error on the last part of the installer when creating a user.

(1/1) BadMethodCallExceptionMethod [syncRoles] does not exist in Controller.php (line 82)

... an a long list of errors.

Here's my step on installing AdaptCMS:

- git clone https://github.com/adaptcms/AdaptCMS.git adaptcms
- cd adaptcms/public
- valet link adaptcms
- composer update
- went to my browser: adaptcms.dev
- I went ahead with the installer form until I got to last step of the install form, create a user.

**Comment by charliepage88** [comment]
Hey,

Thanks a lot for reporting this error. I'm in the middle of working on the CMS right now actually, so once I get at a stopping point I'll check that out and hopefully will have a fix for this tonight, if not, then tomorrow.

Thanks again.

**Comment by illuminate3** [comment]
I realize that you are still working on this but wanted to let you know that the installer is crashing on line 93 of the InstallController.

`$this->syncRoles(['admin', 'demo', 'member', 'editor']);`

looks like spatie isn't fully implemented ...

**Comment by charliepage88** [comment]
sorry for the delay, been dealing with internet issues since we got hit by a tropical storm. It was a simple mistake of the wrong variable name, the $this context has no relevance to roles since it's a controller object. updated correctly to $user, which does have access to roles.

I'll be doing more debugging tonight to see if any other installation issues exist before releasing the beta pubicly.

**Comment by illuminate3** [comment]
Sorry to hear about that. I hope that you and yours are all well. I didn't think that the storms would have gotten to you. I live pretty close to Taylor and see him every so often while shopping or eating out. He likes Moes. I'm a northern by birth though.

I thought I was being dumb because I tried that. But just in case I reran the installer (deleted all tables) and got this error instead.
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (, App\Modules\Users\Models\User, 3))
```
Would you mind posting a dump of a demo database? I'd love to dig in and see what is going on and provide issues or what ever.

**Comment by illuminate3** [comment]
Ok .. here is what I did ...

migration: 2020_..._Roles.php
added:
```
            $table->string('guard_name');
```
I didn't bother setting a column length because I was just trying to get in.

InstallController.php
```
            $user->status = 1;
            $user->save();
            $user->syncRoles(['admin', 'demo', 'member', 'editor']);
            // $user->save();
```

Notice that I moved the save before the sync.

I still haven't looked around but I was able to create a user with the installer wizard and logged in.

**Comment by charliepage88** [comment]
Thanks a lot for looking into this - is the installation working completely for you now?

I saw the problem with the save needing to occur before syncing the roles, but not the migration adjustment - I'll commit that to the repo shortly.

**Comment by illuminate3** [comment]
Installation seems to be working. I was able to go through all steps.

adaptBB seems to be broken ... but I did upgrade it first.

I am still looking around at other things.

**Comment by charliepage88** [comment]
Since the installation is good, I'm going to close this and create a new issue containing the currently known issues that need to be fixed before releasing the Beta. Feel free to list any problems you find there.

If the list is small, then I should be able to knock it out tomorrow and release.
